[package]
name = "udy-cream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.softfloat-wrapper]
version="0.3.4"
default-features=false
features=["riscv"]
